CREATE TABLE spring_boot_plus.test
(
    ID           BIGINT         NOT NULL AUTO_INCREMENT COMMENT '主键',
    CODE         VARCHAR(20) COMMENT '编号',
    DEFAULT_NAME VARCHAR(50) DEFAULT 'A' COMMENT '名称',
    NAME         VARCHAR(50) COMMENT '名称',
    O_NAME       VARCHAR(50) COMMENT '原列表',
    SALARY       DECIMAL(10, 2) NOT NULL COMMENT '精度',
    SALARY_12    DECIMAL(10, 2) NOT NULL COMMENT '精度',
    DEL_COL      VARCHAR(50) COMMENT '删除',
    CREATE_TIME  DATETIME    DEFAULT COMMENT '创建时间',
    PRIMARY KEY (ID)
)